[theme]
base = "light"
primaryColor = "#087f8c"
backgroundColor = "#f5f7fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#172438"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
showEmailPrompt = false
